name = "websocket-worker"
main = "src/index.ts"
compatibility_date = "2024-07-01"

[[durable_objects.bindings]]
name = "WEBSOCKET_ROOM"
class_name = "WebsocketRoomDurableObject"

[[migrations]]
tag = "v1"
new_classes = ["WebsocketRoomDurableObject"]
