name = "websocket-worker"
main = "src/index.ts"
compatibility_date = "2024-07-01"

[[durable_objects.bindings]]
name = "WEBSOCKET_ROOM"
class_name = "WebsocketRoomDurableObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["WebsocketRoomDurableObject"]

[[d1_databases]]
binding = "DB"
database_name = "feliz-natal"
database_id = "6aab0390-a39d-468a-9cb6-2e6b8093d8a8"
