name = "feliz-natal-app"
compatibility_date = "2024-10-01"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = "./dist"

[vars]
# Add any environment variables you want to expose to the Worker here.

[[d1_databases]]
binding = "DB"
database_name = "feliz-natal"
database_id = "6aab0390-a39d-468a-9cb6-2e6b8093d8a8"
migrations_dir = "./migrations"

[[kv_namespaces]]
binding = "API_CACHE"
id = "b657448077cc411f83c7bed0378e66dd"
